use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR must be set");
    let crate_dir = Path::new(&manifest_dir);
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR must be set");
    let registry_path = Path::new(&out_dir).join("demo_registry.rs");
    let demos = discover_demos(crate_dir);

    println!("cargo:rerun-if-changed=.");

    let mut generated = String::new();
    generated.push_str("// Generated by build.rs from demo_*/mod.rs folders.\n\n");

    for demo in &demos {
        let module_path = crate_dir
            .join(demo)
            .join("mod.rs")
            .display()
            .to_string()
            .replace('\\', "/");
        generated.push_str(&format!("#[path = \"{module_path}\"]\n"));
        generated.push_str(&format!("mod {demo};\n"));
    }

    generated.push_str("\n");

    for demo in &demos {
        generated.push_str(&format!("impl demo_runtime for {demo}::State {{\n"));
        generated.push_str("    fn render_hud(&self) -> DemoHud {\n");
        generated.push_str(&format!(
            "        let mut hud = {demo}::render_hud(self);\n"
        ));
        generated.push_str(&format!(
            "        hud.demo_hud_text = format!(\"{demo}: {{}}\", hud.demo_hud_text);\n"
        ));
        generated.push_str("        hud\n");
        generated.push_str("    }\n\n");
        generated.push_str("    fn window_event(&mut self, app: &App, event: &WindowEvent) {\n");
        generated.push_str(&format!(
            "        {demo}::window_event(app, self, event);\n"
        ));
        generated.push_str("    }\n\n");
        generated
            .push_str("    fn view(&self, app: &App, draw: &Draw, viewport: AspectViewport) {\n");
        generated.push_str(&format!(
            "        {demo}::view(app, self, draw, viewport);\n"
        ));
        generated.push_str("    }\n");
        generated.push_str("}\n\n");
    }

    generated.push_str("fn demo_count() -> usize {\n");
    generated.push_str(&format!("    {}\n", demos.len()));
    generated.push_str("}\n\n");

    generated.push_str("fn create_demo_state(index: usize) -> demo_state {\n");
    generated.push_str("    match index {\n");
    for (index, demo) in demos.iter().enumerate() {
        generated.push_str(&format!(
            "        {index} => demo_state::from_inner(Box::new({demo}::State::new())),\n"
        ));
    }
    let fallback_demo = demos.first().expect("demo list is never empty");
    generated.push_str(&format!(
        "        _ => demo_state::from_inner(Box::new({fallback_demo}::State::new())),\n"
    ));
    generated.push_str("    }\n");
    generated.push_str("}\n");

    fs::write(registry_path, generated).expect("failed to write demo registry");
}

fn discover_demos(crate_dir: &Path) -> Vec<String> {
    let mut demos = fs::read_dir(crate_dir)
        .expect("failed to read hot_reload crate directory")
        .filter_map(Result::ok)
        .filter(|entry| {
            entry
                .file_type()
                .map(|file_type| file_type.is_dir())
                .unwrap_or(false)
        })
        .filter_map(|entry| {
            let name = entry.file_name().to_string_lossy().to_string();
            let has_demo_name = name.strip_prefix("demo_").is_some_and(|suffix| {
                !suffix.is_empty() && suffix.chars().all(|ch| ch.is_ascii_digit())
            });
            let has_mod = entry.path().join("mod.rs").is_file();

            if has_demo_name && has_mod {
                Some(name)
            } else {
                None
            }
        })
        .collect::<Vec<_>>();

    demos.sort();

    if demos.is_empty() {
        panic!("expected at least one demo_*/mod.rs folder");
    }

    demos
}
